platform :ios, "7.0"
xcodeproj "JKGDynamicTypeManagerExample/JKGDynamicTypeManagerExample.xcodeproj"
pod "JKGDynamicTypeManager", :path => "../JKGDynamicTypeManager.podspec"

#target "Demo" do
#end

#target "DemoTests" do
#end
